# 此 GitHub Workflow 的功能是將指定文件複製到名為 [package] 的文件夾中，並將其打包成 ZIP 文件，以供後續工作流程使用。使用說明：
# 1. 將此文件保存為 .github/workflows/1.BuildAndPackage.yml。
# 2. 當推送到 main 分支時，此工作流程將自動執行。

name: 1.BuildAndPackage

on:
  push:
    branches:
      - main  # 根據需要調整觸發條件和分支

jobs:
  package_files:
    runs-on: ubuntu-latest

    steps:
      # 檢出代碼
      - name: 檢出代碼
        uses: actions/checkout@v2

      # 創建打包文件夾
      - name: 創建打包文件夾
        run: mkdir package

      # 複製文件到打包文件夾
      - name: 複製文件到打包文件夾
        run: |
          cp LICENSE package/LICENSE
          cp README.md package/README.md
          cp source/Cfg_Docker/dockerfile package/dockerfile
          cp source/Scr_SimpleDemoBox/SimpleDemoBox.sh package/SimpleDemoBox.sh

      # 打包ZIp上傳文件
      - name: 上傳打包文件
        uses: actions/upload-artifact@v4
        with:
          name: package 
          path: package
