# 此 GitHub Workflow 的功能是將指定文件複製到名為 [package] 的文件夾中，並將其打包成 ZIP 文件，以供後續工作流程使用。使用說明：
# 1. 將此文件保存為 .github/workflows/2.ModuleTest.yml。
# 2. 當推送到 main 分支時，此工作流程將自動執行。

name: 2.ModuleTest

on:
  workflow_run:
    workflows: ["1.ModulePackage"]
    types: [completed]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # 檢查上一個工作流程的狀態
      - name: Check previous workflow status
        id: check_status
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "failure" ]; then
            echo "Previous workflow failed. Exiting."
            exit 1
          else
            echo "Previous workflow succeeded. Continuing."
          fi

      # 下載上一個工作流程的產物
      - name: Get artifact from previous workflow
        uses: actions/download-artifact@v2
        with:
          name: package

      # 構建及執行 Docker 容器
      - name: Build and run Docker container
        run: |
          docker build -t myapp package/
          docker run -d --name myapp-container myapp

      # 執行測試
      - name: 執行容器外測試
        run: |
          pytest source/Scr_SimpleDemoBox_Test/Scr_SimpleBox_Test.py