# 說明: 這個 GitHub Action 文件 "2.ModuleTest" 是用來在 "1.ModulePackage" 工作流程成功後，自動化地構建和測試 Docker 容器。
#       請按照以下步驟將此文件放入您的 GitHub 儲存庫中的 .github/workflows 目錄下。

name: 2.ModuleTest

on:
  workflow_run:
    workflows: ["1.ModulePackage"]
    types: [completed]
     # 僅成功時執行
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # 下載最新的預發布包文件
      - name: 下載最新預發布包
        uses: actions/download-artifact@v2
        with:
          name: pre-release-package
          path: pre-release

      # 構建 Docker 容器
      - name: 構建 Docker 容器
        run: |
          docker build -t my-app ./pre-release

      # 運行 Docker 容器
      - name: 運行 Docker 容器
        run: |
          docker run -d --name my-running-app my-app

      # 使用 pytest 測試 Docker 容器
      - name: 使用 pytest 測試容器
        run: |
          docker exec my-running-app pytest /source/Scr_SimpleDemoBox_Test/Scr_SimpleBox_Test.py
