# 這是一個GitHub Action工作流程檔案，當[2.ModuleTest]工作流程完成後會被觸發。
# 如果[2.ModuleTest]工作流程失敗，這個工作流程會顯示錯誤訊息並以失敗結束。
# 如果[2.ModuleTest]工作流程成功，則會繼續執行下面的工作，包括取得前一工作流程上傳的成品(artifact)並創建一個發布(release)。

name: 3.ModuleRelease

# 觸發條件設定為workflow_run，指定在[2.ModuleTest]工作流程完成後執行
on:
  workflow_run:
    workflows: ["2.ModuleTest"]
    types:
      - completed

jobs:
  check_previous_workflow:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - name: Echo failure message
        run: echo "前一個工作流程[2.ModuleTest]失敗了。"

  release:
    needs: check_previous_workflow
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Echo success message
        run: echo "前一個工作流程[2.ModuleTest]成功了。"

      # 下載前一工作流程的成品(artifact)
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package

      # 創建發布(release)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
