# 使用方式：将此文件存放在您的 GitHub 仓库的 .github/workflows 目录下，命名为 build_test.yml

name: BuildTest

on:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check BoxSetting.sh existence
        run: test -f source/Scr-SimpleBox/BoxSetting.sh && echo "BoxSetting.sh exists." || echo "BoxSetting.sh does not exist."
