# 使用方式：將此GitHub Action設定檔案儲存於您的儲存庫中的.github/workflows目錄下。當您向main分支推送時，此動作將自動運行，檢查指定的檔案是否存在。

name: 檢查檔案存在性

on:
  push:
    branches:
      - main  # 可以根據需要修改觸發分支

jobs:
  check_files:
    runs-on: ubuntu-latest  # 運行環境為最新版的Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 使用actions/checkout@v2這個Action來檢出代碼

      - name: 檢查 dockerfile.txt 是否存在
        run: |
          if [ -f source/Cfg-Docker/dockerfile.txt ]; then
            echo "dockerfile.txt 存在."
          else
            echo "錯誤：dockerfile.txt 不存在."
            exit 1  # 如果檔案不存在，則退出狀態為1
          fi

      - name: 檢查 BoxSetting.sh 是否存在
        run: |
          if [ -f source/Scr-SimpleBox/BoxSetting.sh ]; then
            echo "BoxSetting.sh 存在."
          else
            echo "錯誤：BoxSetting.sh 不存在."
            exit 1  # 如果檔案不存在，則退出狀態為1
          fi
