# 此 GitHub Workflow 的功能是將指定文件複製到名為 releasePackage 的文件夾中，然後使用這些文件來構建和運行 Docker 容器，並進行測試。使用說明：
# 1. 將此文件保存為 .github/workflows/moduleTest.yml。
# 2. 當推送到 main 分支或 pull request 事件發生時，此工作流程將自動執行。

name: moduleTest

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # 檢出代碼
      - name: 檢出代碼
        uses: actions/checkout@v2

      # 打包步驟
      - name: 打包文件
        run: |
          mkdir releasePackage
          cp LICENSE README.MD src/Cfg_Docker/dockerfile src/scr_paperPassBox/boxInitialize.sh releasePackage/

      # 上傳打包文件(upload-artifact已自動zip)
      - name: 上傳打包文件
        uses: actions/upload-artifact@v4
        with:
          name: releasePackage
          path: releasePackage

      # 部署及執行Docker容器
      - name: 部署及執行 Docker 容器
        run: |
          cp ./releasePackage ./deployment
          cd deployment
          docker build -t myapp:latest .
          docker run -d -p 2222:22 --name myapp_container myapp:latest

      # 準備測試環境(須配合pipenv版本)
      - name: 準備 Python 測試環境
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'

      # 執行測試
      - name: 執行測試
        run: |
          cp -R src/scr_paperPassBox_test test
          cd test
          pip install pipenv
          pipenv install --deploy --ignore-pipfile
          pipenv run pytest
